SELECT BOOKNAME
FROM BOOK
WHERE PRICE = (SELECT MAX(PRICE) FROM BOOK);

SELECT NAME
FROM CUSTOMER
WHERE CUSTID IN (SELECT CUSTID FROM ORDERS);

--1.5
SELECT PUBLISHER
FROM BOOK
WHERE BOOKID IN (SELECT BOOKID
                    FROM ORDERS 
                    WHERE CUSTID IN (SELECT CUSTID
                                        FROM CUSTOMER
                                        WHERE NAME = '박지성'));
                                        
--1.6
SELECT BOOKNAME, PRICE, SALEPRICE, PRICE-SALEPRICE
FROM BOOK, ORDERS, CUSTOMER
WHERE BOOK.BOOKID = ORDERS.BOOKID AND ORDERS.CUSTID = CUSTOMER.CUSTID AND NAME = '박지성';

--1.7
SELECT BOOKNAME
FROM BOOK, ORDERS, CUSTOMER
WHERE BOOK.BOOKID = ORDERS.BOOKID AND ORDERS.CUSTID = CUSTOMER.CUSTID AND NAME != '박지성';

--2.8
SELECT NAME
FROM CUSTOMER
WHERE CUSTID NOT IN (SELECT CUSTID FROM ORDERS);

--2.9
SELECT SUM(SALEPRICE), AVG(SALEPRICE)
FROM ORDERS;

--2.10
SELECT NAME, SUM(SALEPRICE)
FROM CUSTOMER, ORDERS
WHERE CUSTOMER.CUSTID = ORDERS.CUSTID
GROUP BY NAME;

--2.11
SELECT NAME, BOOKNAME
FROM BOOK, ORDERS, CUSTOMER
WHERE BOOK.BOOKID = ORDERS.BOOKID AND ORDERS.CUSTID = CUSTOMER.CUSTID;

--2.12 
SELECT ORDERID
FROM BOOK, ORDERS
WHERE BOOK.BOOKID = ORDERS.BOOKID AND PRICE-SALEPRICE IN (SELECT MAX(PRICE-SALEPRICE)
                                        FROM BOOK, ORDERS
                                        WHERE BOOK.BOOKID = ORDERS.BOOKID);

--2.13
SELECT NAME, AVG(SALEPRICE)
FROM BOOK, ORDERS, CUSTOMER
WHERE BOOK.BOOKID = ORDERS.BOOKID AND ORDERS.CUSTID = CUSTOMER.CUSTID 
GROUP BY NAME
HAVING AVG(SALEPRICE) > (SELECT AVG(PRICE)
                        FROM BOOK, ORDERS
                        WHERE BOOK.BOOKID = ORDERS.BOOKID);

SELECT NAME
FROM CUSTOMER
MINUS
SELECT NAME
FROM CUSTOMER
WHERE CUSTID IN (SELECT CUSTID
                FROM ORDERS);
